site_name: KubeSail Docs
theme: readthedocs
repo_url: https://github.com/kubesail/docs
nav:
  - Home: README.md
  - Getting Started: 
    - 'Set up a namespace': namespace.md
    - 'Deploy your app': deploy.md
  - Advanced Topics: 
    - 'Custom domains': domains.md
    - 'Exposing your app': exposing.md
  - Definitions: 'definitions.md'
  - Contributing: contributing.md
extra_css:
  - extra.css
