site_name: KubeSail Docs
theme: readthedocs
repo_url: https://github.com/kubesail/docs
nav:
  - Home: README.md
  - Getting Started:
      - 'Set up a namespace': namespace.md
      - 'Deploy your app': repo_builder.md
  - Advanced Topics:
      - 'Custom domains': domains.md
      - 'Exposing your app': exposing.md
      - 'Deployment options': deploy.md
  - Definitions: 'definitions.md'
  - Bring Your Own Cluster: 'byoc.md'
  - Contributing: contributing.md
extra_css:
  - extra.css
google_analytics: ['UA-131519845-2', 'docs.kubesail.com']
